### ISSUE TITLE
Class 'App\Http\Controllers\Gmaps' not found

### ISSUE THREAD

**Issue by almamundinajpuri** [appitventures/Phpgmaps#16]
Hello,
I'm getting the following error while using Gmap:: in controller
```
FatalErrorException in ListingController.php line 33:
Class 'App\Http\Controllers\Gmaps' not found
```
But if I use Gmap class in my views, it works.
Could you give me some hint what I'm am doting wrong.

Regards.

**Comment by MemonFaysal** [comment]
In controller file just type  use Gmap;

**Comment by almamundinajpuri** [comment]
Hi Foysal,

You mean 'use Gamps' ?
Thanks for the quick response. It worked.

**Comment by MemonFaysal** [comment]
You welcome dear
