### ISSUE TITLE
quick modification for your example in Readme.md

### ISSUE THREAD

**Issue by thetitoo** [appitventures/Phpgmaps#3]
Hullo,

just a quick one: in your Readme.md file you should replace:
```echo "<html><head>".$map['js']."</head><body>".$map['html']."</body></html>";```
by
```echo "<html><head><script type="text/javascript">var centreGot = false;</script>".$map['js']."</head><body>".$map['html']."</body></html>";```

**Comment by michael-hopkins** [comment]
taken care of. thank you
