### ISSUE TITLE
Laravel 4.2 compatibility

### ISSUE THREAD

**Issue by chanderp** [appitventures/Phpgmaps#8]
Can you add a tag or a release for a stable version in laravel 4.2? So i can include it into my projekt. Thank you.

**Comment by marko89kv** [comment]
Same here, please make it work on Laravel 4.2. Thanks.

**Comment by michael-hopkins** [comment]
I'll right. I'll see what I can do

**Comment by russellraed** [comment]
Was this available for 4.2 days ago? My colleague was able to include it in our project before laravel 5 was out. Thanks.

**Comment by russellraed** [comment]
sorry. just saw that you added the l5 requirement 2 days ago. will be waiting for the fix. thanks.

**Comment by stanwarri** [comment]
When are you releasing a Laravel 4.2 compatibility version. I believe you should have left the main branch for 4.2 since lots of people using your package are this version. L5 is still new, and don't think people have migrated their app to that version.

**Comment by iBotPeaches** [comment]
I had to do an emergency fork of the project and revert all the L5 changes to put it in a suitable state for 4.2 projects. 

```
git tag -a v1.0.0 c5f819704a15a43451551ae465986bb1b98a1a67 -m 'Laravel 4.2 Support'
git tag -a v2.0.0 7ce62c4d1e2197d61cccee5bb2b549799bcc9f44 -m 'Laravel 5 Support'
git push --tags origin master
```

I believe that should work.

**Comment by michael-hopkins** [comment]
Will be resolved today

**Comment by michael-hopkins** [comment]
this will be resolved for you guys by adjusting your composer.json to reflect the following line. 
 
`"appitventures/phpgmaps": "1.0.*@dev"`

**Comment by russellraed** [comment]
I am now able to update. Thanks @michael-hopkins
